package com.example.ui.theme

import androidx.compose.ui.graphics.Color

// Safe Start Primary & Secondary Tokens
val TnPrimary = Color(0xFF003528)
val TnOnPrimary = Color(0xFFFFFFFF)
val TnPrimaryContainer = Color(0xFF0A4D3C)
val TnOnPrimaryContainer = Color(0xFFFFFFFF)
val TnPrimaryFixed = Color(0xFFB2EFD8)
val TnPrimaryFixedDim = Color(0xFFC2F5E2)
val TnOnPrimaryFixed = Color(0xFF002117)

val TnSecondary = Color(0xFF795900)
val TnOnSecondary = Color(0xFFFFFFFF)
val TnSecondaryContainer = Color(0xFFFFC641)
val TnOnSecondaryContainer = Color(0xFF382900)
val TnSecondaryFixed = Color(0xFFFFDFA0)

val TnTertiary = Color(0xFF1E293B)
val TnOnTertiary = Color(0xFFFFFFFF)
val TnTertiaryContainer = Color(0xFF334155)
val TnOnTertiaryContainer = Color(0xFFF1F5F9)

val TnSurface = Color(0xFFF8FAFC)
val TnSurfaceVariant = Color(0xFFE2E8F0)
val TnOnSurface = Color(0xFF0F172A)
val TnOnSurfaceVariant = Color(0xFF1E293B)
val TnSurfaceContainerLowest = Color(0xFFFFFFFF)
val TnSurfaceContainerLow = Color(0xFFF1F5F9)
val TnSurfaceContainer = Color(0xFFE2E8F0)
val TnSurfaceContainerHigh = Color(0xFFCBD5E1)
val TnSurfaceContainerHighest = Color(0xFF94A3B8)
val TnSurfaceDim = Color(0xFFCBD5E1)

val TnOutline = Color(0xFF475569)
val TnOutlineVariant = Color(0xFF64748B)

val TnError = Color(0xFFB91C1C)
val TnOnError = Color(0xFFFFFFFF)
val TnErrorContainer = Color(0xFFFEE2E2)
val TnOnErrorContainer = Color(0xFF7F1D1D)

// Indian Government E-Governance Portal Design Tokens
val GovDeepGreen = Color(0xFF0E7C4A)
val GovGreen = Color(0xFF0E7C4A)
val GovDeepGreenDark = Color(0xFF095A34)
val GovDarkNavy = Color(0xFF0B1220)
val GovNavyDark = Color(0xFF0B1220)
val GovTopBarBlack = Color(0xFF0B0F19)
val GovSaffronGold = Color(0xFFF59E0B)
val GovSaffronGoldDark = Color(0xFFD97706)
val GovGoldAccent = Color(0xFFFBBF24)
val GovGoldText = Color(0xFFB45309)
val GovAlertRed = Color(0xFFDC2626)
val GovAlertRedBg = Color(0xFFFEE2E2)
val GovVerifiedGreen = Color(0xFF15803D)
val GovVerifiedGreenBg = Color(0xFFDCFCE7)
val GovLightGreenTabBg = Color(0xFFECFDF5)
val GovPaleBlueBg = Color(0xFFE0F2FE)
val GovPaleBlueBorder = Color(0xFFBAE6FD)
val GovPaleBlueIcon = Color(0xFF0284C7)
val GovPaleGreenBg = Color(0xFFECFDF5)
val GovCalloutBgGreen = Color(0xFFECFDF5)
val GovPaleGreenBorder = Color(0xFFA7F3D0)
val GovPaleGreenIcon = Color(0xFF047857)
val GovGrayBorder = Color(0xFFCBD5E1)
val GovBorderLight = Color(0xFFCBD5E1)
val GovGrayText = Color(0xFF64748B)
val GovTextSecondary = Color(0xFF475569)
val GovDarkText = Color(0xFF0F172A)
val GovTextDark = Color(0xFF0F172A)
val GovOffWhite = Color(0xFFF8FAFC)
val GovCanvasBg = Color(0xFFF8FAFC)
val GovPureWhite = Color(0xFFFFFFFF)

// Government / Civic Health Custom Domain Tokens
val TnDeepTeal = Color(0xFF0E7C4A)
val TnTealHover = Color(0xFF095A34)
val TnTealSubtle = Color(0xFFECFDF5)
val SovereignGold = Color(0xFFF59E0B)
val SovereignGoldLight = Color(0xFFFEF9C3)
val SovereignGoldDark = Color(0xFFD97706)
val SlateCouncil = Color(0xFF0B1220)
val SlateBorder = Color(0xFFCBD5E1)
val SlateSurface = Color(0xFFF8FAFC)
val ClinicalMintBg = Color(0xFFECFDF5)
val BiometricVerified = Color(0xFF15803D)
val BiometricVerifiedBg = Color(0xFFDCFCE7)
val AmberCountdown = Color(0xFFF59E0B)
val AmberCountdownBg = Color(0xFFFFFBEB)
val CrimsonAlert = Color(0xFFDC2626)
val CrimsonAlertBg = Color(0xFFFEE2E2)

